### ISSUE TITLE
BOB Token submission

### ISSUE THREAD

**Issue by bob9090** [iotexproject/ioTube#24]
# ioTube Token submission

## Blockchains you want to bridge from

- IoTeX: <io1fs9py0ck0e8jjyl0eh7sqj56r0knaswd0s746d>

## Blockchains I want to bridge to

- IoTeX
- Ethereum
- Binance Smart Chain
- Polygon
- Huobi Eco Chain

**Comment by simonerom** [comment]
Closing as a duplicate
