### ISSUE TITLE
BOB Token submission

### ISSUE THREAD

**Issue by bob9090** [iotexproject/ioTube#25]
# ioTube Token submission

## Team / Developer name
Bob

## Token Symbol
BOB

## Token Name
BOB Token

## Link to the token icon
https://user-images.githubusercontent.com/82981927/123003783-ffd9c280-d3b3-11eb-9056-bc50ac7e52bd.png

## Short description of your project
Create online store that will work using BOB token as a currency

## What is the native blockchain for your token
IoTeX Blockchain

## Token native contract address
io1fs9py0ck0e8jjyl0eh7sqj56r0knaswd0s746d

## Your project websites
https://www.bob-crypto.com/

## Your social channels
Twitter: https://twitter.com/BobCryptoIOT 
Telegram: https://t.me/joinchat/2qNEa1sjTMIyNTM0

## Blockchains you want to bridge from

- IoTeX: io1fs9py0ck0e8jjyl0eh7sqj56r0knaswd0s746d

## Blockchains I want to bridge to

* [x] Ethereum
* [x] Binance Smart Chain
* [x] Polygon
* [x] Huobi Eco Chain (coming soon)

**Comment by simonerom** [comment]
I will close this request as we currently do not accept new token submissions from the community. We will make this available in the future.
