### ISSUE TITLE
MIST

### ISSUE THREAD

**Issue by alchemlstcoin** [iotexproject/ioTube#29]
# ioTube Token submission

## Team / Developer name
alchemist

## Token Symbol
 MIST

## Token Name in full
Alchemist

## Link to the token icon
https://assets.coingecko.com/coins/images/14655/small/79158662.png?1617589045

## Short description of your project
⚗️'s one and only purpose is to find the philosopher's stone and use it to explore the galaxy.

## What is the native blockchain for your token
* [x] Ethereum
* [ ] Binance Smart Chain
* [ ] Polygon
* [ ] Huobi Eco Chain (coming soon)

## Token native contract address
Address: 0x88ACDd2a6425c3FaAE4Bc9650Fd7E27e0Bebb7aB

## Your project websites
- https://crucible.alchemist.wtf/

## Your social channels
- Telegram:
- Twitter: https://twitter.com/_alchemistcoin
- Discord: http://discord.alchemist.wtf/

## If your token is not native to IoTeX

* [x] Ethereum → IoTeX: 0x88acdd2a6425c3faae4bc9650fd7e27e0bebb7ab
* [ ] Binance Smart Chain → IoTeX: <token contract address on BSC>
* [ ] Polygon → IoTeX: <token contract address on Polygon>
* [ ] Huobi Eco Chain (coming soon) → IoTeX: <token contract address on HEC>

**Comment by guo** [comment]
Thanks for your submission. 
As talked on Telegram, we will add your token to ioTube with source token MIST from ETH. This will create a proxy XRC20 token called MIST on IoTeX. This token will be the corresponding token, not the one you have created and submitted to @iotexproject/iotex-token-metadata.

Please confirm before we proceed. Thanks!

**Comment by alchemlstcoin** [comment]
ok yes sir there is no problem

**Comment by guo** [comment]
this account seems fake. closing now.
