### ISSUE TITLE
add GLAD token

### ISSUE THREAD

**Issue by gladiusfynance** [iotexproject/ioTube#30]
# ioTube Token submission

## Team / Developer name
Gladius Finance

## Token Symbol
GLAD

## Token Name in full
Gladius Finance

## Link to the token icon
https://raw.githubusercontent.com/tomochain/tokens/master/tokens/0xf35f3d0823363c343d8e46bd6cc5f78da014c929.png

## Short description of your project
GLADIUS FINANCE is a fusion between a DeFi Yield Farming and a NFTs Gaming dApp, aim at solving the problems that overshadowed Yield Farming platforms.

## What is the native blockchain for your token
* [ ] Ethereum
* [ ] Binance Smart Chain
* [ ] Polygon
* [ ] Huobi Eco Chain (coming )
* [x] TomoChain

## Token native contract address
Address:0xF35F3D0823363c343D8e46bD6Cc5f78Da014c929

## Your project websites
- https://gladius.finance/

## Your social channels
- Telegram: https://t.me/GladiusFinanceOfficial
- Twitter: https://twitter.com/gladiusfinance
- Medium: https://gladiusfinance.medium.com/

## If your token is not native to IoTeX

* [] Ethereum → IoTeX: <token contract address on Ethereum>
* [ ] Binance Smart Chain → IoTeX: <token contract address on BSC>
* [ ] Polygon → IoTeX: <token contract address on Polygon>
* [ ] Huobi Eco Chain (coming soon) → IoTeX: <token contract address on HEC> 
* [x]TomoChain → IoTeX: 0xF35F3D0823363c343D8e46bD6Cc5f78Da014c929

**Comment by guo** [comment]
Hello @gladiusfynance , thanks for submission. We don't support tomochain at this moment yet. 
Do you have token on supported chain? ETH, BSC. Polygon.

Also, your website does not work. Neither does your medium.
