### ISSUE TITLE
Issue with transferring between ETH and IoTex

### ISSUE THREAD

**Issue by BrianAudits** [iotexproject/ioTube#8]
I am copying a message I sent on discord. This explains the issue. The solution would be to make it so that the ETH goes from the metamask account and transfers the IoTex to the io pay address. It currently transfers it to the io equivalent address of the metamask ETH address. I verified that here: https://member.iotex.io/tools/address-convert

Message from discord below:
Looks like iotube does not work (it appears to be broken). I just lost 0.1 eth that I wrapped to weth and then sent to an address. You cannot select the address to send to. I have my iopay app as well as an ERC20 wallet through metamask. If I try to convert from IoTex to Ethereum, it uses my io address from the iopay app. The ERC20 address that it wants to convert to (I used the address converter on IoTex website to find out that it is the ETH address equivalent to my io address on iopay app), which I do not have access to. When I try to convert from Ethereum to IoTex which I actually did, it converts from the ETH address in my wallet to the io equivalent address for that ETH address and I have no way of accessing that io address. If anyone knows how to fix this issue, please speak up because I'm out $40 due to this app that looks to be broken. I initially thought I got scammed because I didn't recognize the address, but I researched as much as I could and found out otherwise so I'm sharing to help others not lose their money by trying to figure out how to buy ioeth, iotx, and vita. It should not be so difficult to get crypto.... I spent 2 hours trying to get some iotx and vita, and instead lost $40 and got nothing. Very disappointed, but if anyone can help me recover or explain what I'm missing to access my funds, it'd be appreciated.

**Comment by strich20** [comment]
I found the exact same problem as you. I swapped a lot of ERC20 IOTeX for native IOTeX but it was sent to an address that I'm unable to access! I was hoping i could use IOTube to convert it to ETH but its functionality appears limited or is broken.  
Really need some help here please!!!

**Comment by CoderZhi** [comment]
@BrianAudits Ethereuem and IoTeX have the same private key format, and "the ETH address equivalent to my io address" shares the same private key. Vice versa, "the ETH address in my wallet to the io equivalent address for that ETH address" share the same private key. As long as you have the "private key" of one account of the account pairs, you can use it for the other one.
@strich20 your case should be the same.
Hope this could resolve your problems. If you have further questions, please attach the corresponding actions (action hash or link) on Ethereum or IoTeX, such that we could have more details.

**Comment by BrianAudits** [comment]
@CoderZhi Unfortunately, that does not work. I have a 12 word phrase that I must enter into my metamask. I used the same exact 12 word phrase on iopay, and I get a different address than the one showing up on iotube. The address on iotube does match the address showing as the io equivalent of my eth address through iotex's address converter, however, when I use the phrase to unlock my ERC20 wallet in iopay, the address is completely different for my io account. I hope this information helps troubleshoot.

**Comment by BrianAudits** [comment]
A very kind person from IoTeX walked me through how to find my private key on my erc20 wallet. I am surprised that the 12 word phrase does not give the same wallet as the the private ket when used in different apps. But regardless, I was able to access my ioeth 👍 The solution to this issue would be to make sure you use the private key. Best of luck to everyone!

**Comment by CoderZhi** [comment]
@strich20 does this solution work for you？

**Comment by strich20** [comment]
I will try later when i reach home.

**Comment by strich20** [comment]
Sorted!  I encountered the same anomaly as Brian when i entered the 12 word phrase for my ERC20 wallet only to end up with a different io address.  Eventually managed to get hold of the right io address after retrieving and using the private key as you have mentioned!  Thank you all for your kind assistance. Much appreciated!
